language: csharp
dist: xenial
mono: 5.2.0
dotnet: 2.2
install:
- export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
- dotnet restore
script:
- dotnet build -c Release
after_success:
  - dotnet pack -c Release ./MangoPay.SDK/MangoPay.SDK.csproj
deploy:
  skip_cleanup: true
  provider: script
  script: nuget push ./MangoPay.SDK/bin/Release/MangoPay.SDK.*.nupkg -ApiKey $NUGET_API_KEY -Source $NUGET_SOURCE
  on:
    branch: release