language: csharp
dist: bionic
mono: 5.2.0
dotnet: 2.2
before_install:
- sudo apt-get update
- sudo apt-get install nuget
install:
- export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
- dotnet restore
- nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
- dotnet build -c Release
#- mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./MangoPay.SDK.Tests/bin/Release/net461/MangoPay.SDK.Tests.dll
after_success:
  - dotnet pack -c Release ./MangoPay.SDK/MangoPay.SDK.csproj
deploy:
  - provider: script
    script: nuget setapikey $NUGET_API_KEY -Source $NUGET_URL
    on:
      branch: release
  - provider: script
    skip_cleanup: true
    script: dotnet nuget push ./MangoPay.SDK/bin/Release/mangopay2-sdk.*.nupkg $NUGET_API_KEY -s $NUGET_SOURCE
    on:
      branch: release
